name: Build
on: push
jobs:
  Job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build libraries
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        dotnet restore
        msbuild -t:Collections461 -p:Configuration=Release -p:Platform="Any CPU"
        msbuild -t:Collections -p:Configuration=Release -p:Platform="Any CPU"
        msbuild -t:Bench\RdStress01 -p:Configuration=Release -p:Platform="Any CPU"
        msbuild -t:Bench\RxBench01 -p:Configuration=Release -p:Platform="Any CPU"
    - uses: actions/upload-artifact@v1
      with:
        name: RunnerOutput-ReleaseBuild
        path: Collections\bin\Release
