name: Build
on: push
jobs:
  Job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Initialize
      run: |
        mkdir TestResults
        dotnet tool install dotnet-reportgenerator-globaltool --global
    - name: Build library
      run: |
        dotnet msbuild -nologo -restore -p:Configuration=Release Collections
        copy Collections\bin\Release\*.nukpg TestResults\
    - name: Build executables
      run: |
        dotnet msbuild -nologo -restore -p:Configuration=Release Bench\RdStress01
        dotnet msbuild -nologo -restore -p:Configuration=Release Bench\RxBench01
    - name: Run coverage suite
      run: dotnet test -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:CoverletOutput=..\TestResults\lcov TestCore
    - name: Generate coverage report
      run: reportgenerator.exe -reports:.\TestResults\lcov.info -targetdir:.\TestResults\CoverageReport\
    - uses: actions/upload-artifact@v1
      with:
        name: KaosCollections-Build
        path: TestResults
