name: Test
on: push
jobs:
  Job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Initialize
      run: |
        mkdir TestResults
    - name: Build library
      run: |
        dotnet msbuild -nologo -restore -p:Configuration=Debug Collections
        copy Collections\bin\Debug\*.nukpg TestResults\
    - name: Build executables
      run: |
        dotnet msbuild -nologo -restore -p:Configuration=Debug Bench\RdStress01
        dotnet msbuild -nologo -restore -p:Configuration=Debug Bench\RxBench01
    - name: Run standard suite
      run: dotnet test -c Debug TestCore
    - name: Cleanup
      run: dotnet clean TestCore -c Debug
    - name: Run BCL compatiblity suite
      run: dotnet test -c Debug -p:DefineConstants=TEST_BCL TestCore
    - uses: actions/upload-artifact@v1
      with:
        name: KaosCollections-Test
        path: TestResults
