name: Test
on: push
jobs:
  Job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run build
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        dotnet restore
        msbuild -t:Collections461 -p:Configuration=Debug -p:Platform="Any CPU"
        msbuild -t:Test461 -p:Configuration=Debug -p:Platform="Any CPU"
    - name: Run unit tests
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        vstest.console Test461\bin\Debug\Test461.dll
    - name: Run BCL compatibility tests
      run: |
        call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        dotnet clean
        msbuild -t:Test461 -p:DefineConstants=TEST_BCL -p:Configuration=Debug -p:Platform="Any CPU"
        vstest.console Test461\bin\Debug\Test461.dll
